"""
Command-line interface for ctypesgen
"""

import argparse

from ctypesgen import (
    messages as msgs,
    options as core_options,
    parser as core_parser,
    printer_python,
    printer_json,
    processor,
    version,
)


def find_names_in_modules(modules):
    names = set()
    for module in modules:
        try:
            mod = __import__(module)
        except Exception:
            pass
        else:
            names.update(dir(mod))
    return names


# FIXME argparse parameters are not ordered consistently...
def main(givenargs=None):
    
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--version",
        action="version",
        version=version.VERSION_NUMBER,
    )

    # Parameters
    parser.add_argument(
        "-i", "--include",
        "--headers",
        dest="headers",
        required=True,
        nargs="+",
        default=[],
        help="Sequence of header files",
    )
    parser.add_argument(
        "-l",
        "--library",
        required=True,
        metavar="LIBRARY",
        help="link to LIBRARY",
    )
    parser.add_argument(
        "-o",
        "--output",
        metavar="FILE",
        help="write wrapper to FILE [default stdout]",
    )
    parser.add_argument(
        "--other-headers",
        nargs="+",
        default=[],
        metavar="HEADER",
        help="include system header HEADER (e.g. stdio.h or stdlib.h)",
    )
    parser.add_argument(
        "-m",
        "--modules",
        "--link-modules",
        dest="modules",
        nargs="+",
        default=[],
        metavar="MODULE",
        help="use symbols from Python module MODULE",
    )
    parser.add_argument(
        "-I",
        "--includedirs",
        dest="include_search_paths",
        nargs="+",
        default=[],
        metavar="INCLUDEDIR",
        help="add INCLUDEDIR as a directory to search for headers",
    )
    parser.add_argument(
        "-L",
        "--universal-libdirs",
        nargs="+",
        default=[],
        metavar="LIBDIR",
        help="Add LIBDIR to the search path (both compile-time and run-time)",
    )
    parser.add_argument(
        "--compile-libdirs",
        nargs="+",
        default=[],
        metavar="LIBDIR",
        help="Add LIBDIR to the compile-time library search path.",
    )
    parser.add_argument(
        "--runtime-libdirs",
        nargs="+",
        default=[],
        metavar="LIBDIR",
        help="Add LIBDIR to the run-time library search path.",
    )
    parser.add_argument(
        "--no-embed-preamble",
        action="store_false",
        dest="embed_preamble",
        help="Do not embed preamble and loader in output file. "
        "Defining --output as a file and --output-language to "
        "Python is a prerequisite.",
    )

    # Parser options
    parser.add_argument(
        # NOTE(geisserml) "cpp" is ambiguous - in this context, it does not refer to c++, but to the C pre-processor
        "--cpp",
        dest="cpp",
        default="gcc -E",
        help="The command to invoke the c preprocessor, including any "
        "necessary options (default: gcc -E)",
    )
    parser.add_argument(
        "--allow-gnu-c",
        action="store_true",
        dest="allow_gnu_c",
        help="Specify whether to undefine the '__GNUC__' macro, "
        "while invoking the C preprocessor.\n"
        "(default: False. i.e. ctypesgen adds an implicit undefine using '-U __GNUC__'.)\n"
        "Specify this flag to avoid ctypesgen undefining '__GNUC__' as shown above.",
    )
    parser.add_argument(
        "-D",
        "--define",
        nargs="+",
        default=[],
        dest="cpp_defines",
        metavar="MACRO",
        help="Add a definition to the preprocessor via commandline",
    )
    parser.add_argument(
        "-U",
        "--undefine",
        nargs="+",
        default=[],
        dest="cpp_undefines",
        metavar="NAME",
        help="Instruct the preprocessor to undefine the specified macro via commandline",
    )
    parser.add_argument(
        "--save-preprocessed-headers",
        metavar="FILENAME",
        dest="save_preprocessed_headers",
        help="Save the preprocessed headers to the specified FILENAME",
    )
    parser.add_argument(
        "--optimize-lexer",
        dest="optimize_lexer",
        action="store_true",
        help="Run the lexer in optimized mode.  This mode requires write "
        "access to lextab.py file stored within the ctypesgen package.",
    )

    # Processor options
    parser.add_argument(
        "-a",
        "--all-headers",
        action="store_true",
        dest="all_headers",
        help="include symbols from all headers, including system headers",
    )
    parser.add_argument(
        "--builtin-symbols",
        action="store_true",
        dest="builtin_symbols",
        help="include symbols automatically generated by the preprocessor",
    )
    parser.add_argument(
        "--no-macros",
        action="store_false",
        dest="include_macros",
        help="Don't output macros.",
    )
    parser.add_argument(
        "--no-undefs",
        action="store_false",
        dest="include_undefs",
        help="Do not remove macro definitions as per #undef directives",
    )
    parser.add_argument(
        "--include-symbols",
        nargs="+",
        default=[],
        metavar="REGEXPR",
        help="Regular expression for symbols to always include.  Multiple "
        "instances of this option will be combined into a single expression "
        "doing something like '(expr1|expr2|expr3)'.",
    )
    parser.add_argument(
        "--exclude-symbols",
        nargs="+",
        default=[],
        metavar="REGEXPR",
        help="Regular expression for symbols to exclude.  Multiple instances "
        "of this option will be combined into a single expression doing "
        "something like '(expr1|expr2|expr3)'.",
    )
    parser.add_argument(
        "--no-stddef-types",
        action="store_true",
        dest="no_stddef_types",
        help="Do not support extra C types from stddef.h",
    )
    parser.add_argument(
        "--no-gnu-types",
        action="store_true",
        dest="no_gnu_types",
        help="Do not support extra GNU C types",
    )
    parser.add_argument(
        "--no-python-types",
        action="store_true",
        dest="no_python_types",
        help="Do not support extra C types built in to Python",
    )
    # TODO turn into dest="load_library" and "store_false"
    parser.add_argument(
        "--no-load-library",
        action="store_true",
        help="Do not try to load library during the processing"
    )

    # Printer options
    parser.add_argument(
        "--header-template",
        dest="header_template",
        metavar="TEMPLATE",
        help="Use TEMPLATE as the header template in the output file.",
    )
    parser.add_argument(
        "--strip-build-path",
        dest="strip_build_path",
        metavar="BUILD_PATH",
        help="Strip build path from header paths in the wrapper file.",
    )
    parser.add_argument(
        "--insert-files",
        dest="inserted_files",
        nargs="+",
        default=[],
        metavar="FILENAME",
        help="Add the contents of FILENAME to the end of the wrapper file.",
    )
    parser.add_argument(
        "--output-language",
        dest="output_language",
        metavar="LANGUAGE",
        default="py",
        choices=("py", "json"),
        help="Choose output language",
    )
    parser.add_argument(
        "--no-srcinfo",
        action = "store_true",
        help = "Skip comments stating where members are defined (header, line)."
    )

    # Error options
    parser.add_argument(
        "--all-errors",
        action="store_true",
        dest="show_all_errors",
        help="Display all warnings and errors even if they would not affect output.",
    )
    parser.add_argument(
        "--show-long-errors",
        action="store_true",
        dest="show_long_errors",
        help="Display long error messages instead of abbreviating error messages.",
    )
    parser.add_argument(
        "--no-macro-warnings",
        action="store_false",
        dest="show_macro_warnings",
        help="Do not print macro warnings.",
    )
    parser.add_argument(
        "--debug-level",
        dest="debug_level",
        default=0,
        type=int,
        help="Run ctypesgen with specified debug level (also applies to yacc parser)",
    )

    parser.set_defaults(**core_options.default_values)
    args = parser.parse_args(givenargs)

    args.compile_libdirs += args.universal_libdirs
    args.runtime_libdirs += args.universal_libdirs

    # Figure out what names will be defined by imported Python modules
    args.other_known_names = find_names_in_modules(args.modules)

    assert args.library

    # Fetch printer for the requested output language
    if args.output_language == "py":
        printer = printer_python.WrapperPrinter
    elif args.output_language == "json":
        printer = printer_json.WrapperPrinter
    else:
        assert False  # handled by argparse choices

    # Step 1: Parse
    descriptions = core_parser.parse(args.headers, args)

    # Step 2: Process
    processor.process(descriptions, args)

    # Step 3: Print
    printer(args.output, args, descriptions)

    msgs.status_message("Wrapping complete.")

    # Correct what may be a common mistake
    if descriptions.all == []:
        if not args.all_headers:
            msgs.warning_message(
                "There wasn't anything of use in the "
                "specified header file(s). Perhaps you meant to run with "
                "--all-headers to include objects from included sub-headers? ",
                cls="usage",
            )


if __name__ == "__main__":
    main()
