name: Test

on:
  workflow_dispatch:
    inputs:
      upload_data:
        default: false
        type: boolean
      cpp:
        default: ''
        type: string

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  setup-and-test:
    name: Python-${{ matrix.python }} ${{ matrix.os }}
    permissions:
      contents: read  # recommended by checkout and setup-python actions
    
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            python: '3.8'
          - os: ubuntu-latest
            python: '3.9'
          - os: ubuntu-latest
            python: '3.10'
          - os: ubuntu-latest
            python: '3.11'
          - os: ubuntu-latest
            python: '3.12'
          - os: ubuntu-latest
            python: '3.13'
          # Linux arm64
          - os: ubuntu-24.04-arm
            python: '3.13'
          # macOS (arm64 and intel)
          - os: macos-latest
            python: '3.13'
          - os: macos-15-intel
            python: '3.13'
          # Windows (x86_64 and arm64)
          - os: windows-latest
            python: '3.13'
          - os: windows-11-arm
            python: '3.13'
    
    runs-on: ${{ matrix.os }}
    steps:
      
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python }}
          pip-install: pytest
      
      - name: Install Python dependencies
        run: |
          python -VV
          python -c "import platform as p; print(p.machine())"
          python -m pip install -v -e .
      
      - name: Run Test
        run: python -m pytest -sv tests/testsuite.py
        env:
          CLEANUP_OK: ${{ !inputs.upload_data && 1 || 0 }}
          CPP: ${{ inputs.cpp }}
      
      - name: Upload generated data
        if: ${{ inputs.upload_data }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: out_${{ matrix.os }}_py${{ matrix.python }}
          path: |
            tests/tmp/
            tests/common/
